<?php 
	return [
		[
			'menu_id'=>'dashboard',
			'menu_name'=>'Dashboard',
			'menu_title'=>'Dashboard',
			'menu_icon'=>'Dashboard',
			'menu_url'=>'#1',
			'menu_parent_id'=>NULL,
			'submenu'=>[],
		],
		[
			'menu_id'=>'examples',
			'menu_name'=>'Examples',
			'menu_title'=>'Plugin Usage',
			'menu_icon'=>'fa fa-users',
			'menu_parent_id' => NULL,
			'menu_url'=>'#',
			'submenu'=>[
				[
					'menu_id'=>'highchart',
					'parent_menu_name'=>'Milo Highchart',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'plugins',
					'menu_action'=>['highchart'],
					'submenu'=>[],
				],
				[
					'menu_id'=>'highchart2',
					'parent_menu_name'=>'Amigos Highchart',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'plugins',
					'menu_action'=>'highchart2',
					'submenu'=>[],
				],
				[
					'menu_id'=>'syntaxhighlighter',
					'parent_menu_name'=>'Syntax Highlighter',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'plugins',
					'menu_action'=>'syntaxhighlighter',
					'submenu'=>[],
				],
				[
					'menu_id'=>'latlongfinder',
					'parent_menu_name'=>'Location Finder',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'plugins',
					'menu_action'=>'latlongfinder',
					'submenu'=>[],
				],
				[
					'menu_id'=>'fileexplorer',
					'parent_menu_name'=>'X Days Ago',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'plugins',
					'menu_action'=>'fileexplorer',
					'submenu'=>[],
				],
			],
		],
		[
			'menu_id'=>'settings',
			'menu_name'=>'Pengaturan',
			'menu_title'=>'Pengaturan',
			'menu_icon'=>'fa fa-users',
			'menu_parent_id' => NULL,
			'menu_url'=>'#',
			'submenu'=>[
				[
					'menu_id'=>'identity',
					'parent_menu_name'=>'Identitas Aplikasi',
					'menu_parent'=>'settings',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'identity',
					'menu_action'=>['index',],
					'submenu'=>[],
				],
			],
		],
		[
			'menu_id'=>'user',
			'menu_name'=>'Users',
			'menu_title'=>'Pengguna',
			'menu_icon'=>'fa fa-users',
			'menu_parent_id' => NULL,
			'menu_url'=>'#',
			'submenu'=>[
				[
					'menu_id'=>'admin',
					'parent_menu_name'=>'Pengguna',
					'menu_parent'=>'user',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'admin',
					'menu_action'=>['index','update','update-profile','info','assignments',],
					'submenu'=>[],
				],
				[
					'menu_id'=>'admin',
					'parent_menu_name'=>'Tambah Pengguna',
					'menu_parent'=>'user',
					'menu_icon'=>'fa fa-user',
					'menu_url'=>'admin',
					'menu_action'=>'create',
					'submenu'=>[],
				],
			],
		],
	]

?>