<?php 
	return [
		[
			'menu_id'=>'dashboard',
			'menu_name'=>'Dashboard',
			'menu_title'=>'Dashboard',
			'menu_icon'=>'Dashboard',
			'menu_url'=>'#1',
			'menu_parent_id'=>NULL,
			'submenu'=>[],
		],
		[
			'menu_id'=>'examples',
			'menu_name'=>'Examples',
			'menu_title'=>'Penggunaan Plugin',
			'menu_icon'=>'fa fa-check',
			'menu_parent_id' => NULL,
			'menu_url'=>'#',
			'submenu'=>[
				[
					'menu_id'=>'highchart',
					'parent_menu_name'=>'Milo Highchart',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>['highchart'],
					'submenu'=>[],
				],
				[
					'menu_id'=>'highchart2',
					'parent_menu_name'=>'Amigos Highchart',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'highchart2',
					'submenu'=>[],
				],
				[
					'menu_id'=>'syntaxhighlighter',
					'parent_menu_name'=>'Syntax Highlighter',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'syntaxhighlighter',
					'submenu'=>[],
				],
				[
					'menu_id'=>'latlongfinder',
					'parent_menu_name'=>'Penemu Lokasi',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'latlongfinder',
					'submenu'=>[],
				],
				[
					'menu_id'=>'fileexplorer',
					'parent_menu_name'=>'Manajemen Berkas',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'fileexplorer',
					'submenu'=>[],
				],
				[
					'menu_id'=>'mobiledetect',
					'parent_menu_name'=>'Deteksi Device',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'mobiledetect',
					'submenu'=>[],
				],
				[
					'menu_id'=>'currency',
					'parent_menu_name'=>'Konversi Kurs',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'currency',
					'submenu'=>[],
				],
				[
					'menu_id'=>'comboyear',
					'parent_menu_name'=>'Dropdown Tahun',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'comboyear',
					'submenu'=>[],
				],
				[
					'menu_id'=>'faker',
					'parent_menu_name'=>'Data Dummy',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'faker',
					'submenu'=>[],
				],
				[
					'menu_id'=>'daysago',
					'parent_menu_name'=>'Waktu Lampau',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'daysago',
					'submenu'=>[],
				],
				[
					'menu_id'=>'soccers',
					'parent_menu_name'=>'Jadwal Bola',
					'menu_parent'=>'examples',
					'menu_icon'=>'fa fa-plug',
					'menu_url'=>'plugins',
					'menu_action'=>'soccers',
					'submenu'=>[],
				],
			],
		],
		[
			'menu_id'=>'settings',
			'menu_name'=>'Pengaturan',
			'menu_title'=>'Pengaturan',
			'menu_icon'=>'fa fa-wrench',
			'menu_parent_id' => NULL,
			'menu_url'=>'#',
			'submenu'=>[
				[
					'menu_id'=>'identity',
					'parent_menu_name'=>'Identitas Aplikasi',
					'menu_parent'=>'settings',
					'menu_icon'=>'fa fa-home',
					'menu_url'=>'identity',
					'menu_action'=>['index',],
					'submenu'=>[],
				],
			],
		],
		[
			'menu_id'=>'user',
			'menu_name'=>'Users',
			'menu_title'=>'Pengguna',
			'menu_icon'=>'fa fa-users',
			'menu_parent_id' => NULL,
			'menu_url'=>'#',
			'submenu'=>[
				[
					'menu_id'=>'admin',
					'parent_menu_name'=>'Pengguna',
					'menu_parent'=>'user',
					'menu_icon'=>'fa fa-users',
					'menu_url'=>'admin',
					'menu_action'=>['index','update','update-profile','info','assignments',],
					'submenu'=>[],
				],
				[
					'menu_id'=>'admin',
					'parent_menu_name'=>'Tambah Pengguna',
					'menu_parent'=>'user',
					'menu_icon'=>'fa fa-user',
					'menu_url'=>'admin',
					'menu_action'=>'create',
					'submenu'=>[],
				],
			],
		],
	]

?>